module.exports = {
    FB_PAGE_TOKEN: '<YOUR_FACEBOOK_PAGE_TOKEN>',
    FB_VERIFY_TOKEN: '<YOUR_VERIFY_TOKEN>',
    FB_APP_SECRET: '<YOUR_FACEBOOK_APP_SECRET>',
    SERVER_URL: '',
    GOOGLE_PROJECT_ID: '<GOOGLE_PROJECT_ID>',
    DF_LANGUAGE_CODE: 'en-US',
    FB_PAGE_INBOX_ID: '<FB_PAGE_INBOX_ID>',
    GOOGLE_CLIENT_EMAIL: '<CLIENT_EMAIL_ACCESS>',
    GOOGLE_PRIVATE_KEY: '<GOOGLE_PRIVATE_KEY>',
};
